In [1]:
import numpy as np

In [14]:
rows, columns = 0, 0
rows = int(input("Enter number of rows: "))
columns = int(input("Enter number of columns: "))

# Read two matrices
print("Matrix1:")
ar = []
i=0
while i < rows:
    tmp = list(map(int, input().split()))
    if(columns == len(tmp)):
        ar.append(tmp)
        i+=1
    else: 
        print("\tEnter ", columns," space seperated elements: ")
mat1 = np.array(ar)

print("Matrix2:")
ar = []
i=0
while i < rows:
    tmp = list(map(int, input().split()))
    if(columns == len(tmp)):
        ar.append(tmp)
        i+=1
    else: 
        print("\tEnter ", columns," space seperated elements: ")
mat2 = np.array(ar)


Enter number of rows: 2
Enter number of columns: 2
Matrix1:
1 1
1
Enter  2  space seperated elements: 
1 1
Matrix2:
1 3
1 
Enter  2  space seperated elements: 
3 4


## 1

In [18]:
print("Dot product: \n", np.dot(mat1, mat2))

Dot product: 
 [[4 7]
 [4 7]]


## 2

In [29]:
print("Transpose of matrix1: \n", np.transpose(mat1))
print("Transpose of matrix2: \n", np.transpose(mat2))

Transpose of matrix1: 
 [[1 1]
 [1 1]]
Transpose of matrix2: 
 [[1 3]
 [3 4]]


## 3

In [28]:
print("Trace of matrix1: \n", np.trace(mat1))
print("Trace of matrix2: \n", np.trace(mat2))

Trace of matrix1: 
 2
Trace of matrix2: 
 5


## 4

In [27]:
from numpy.linalg import matrix_rank

print("Matrix Rank of matrix1: ", matrix_rank(mat1))
print("Matrix Rank of matrix2: ", matrix_rank(mat2))

Matrix Rank of matrix1:  1
Matrix Rank of matrix2:  2


## 5

In [31]:
from numpy.linalg import det

print("Determinant of matrix1: ", det(mat1))
print("Determinant of matrix2: ", det(mat2))

Determinant of matrix1:  0.0
Determinant of matrix2:  -5.000000000000001


## 6

In [36]:
from numpy.linalg import inv

print("Inverse of matrix2: \n", inv(mat2))

Inverse of matrix2: 
 [[-0.8  0.6]
 [ 0.6 -0.2]]


## 7

In [37]:
from numpy.linalg import eig

w, v = eig(mat1)
print("Eigen Values of matrix1: \n", w)
print("Eigen Vectors of matrix1: \n", v)

w, v = eig(mat2)
print("Eigen Values of matrix2: \n", w)
print("Eigen Vectors of matrix2: \n", v)

Eigen Values of matrix1:  [2. 0.]
Eigen Vectors of matrix1:  [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Eigen Values of matrix2:  [-0.85410197  5.85410197]
Eigen Vectors of matrix2:  [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
