## Exercise 1

### Q1

In [3]:
import numpy as np

In [21]:
ar1 = np.array([1, 2, 3, 5, 7])
ar2 = np.array([2, 3, 4, 5, 6])

In [33]:
print("Array1: ", ar1)
print("Array2: ", ar2)
print()

print("Array1 >  Array2: ", np.greater(ar1,ar2))
print("Array1 >= Array2: ", np.greater_equal(ar1, ar2))
print("Array1 <  Array2: ", np.less(ar1, ar2))
print("Array1 >= Array2: ", np.less_equal(ar1, ar2))

Array1:  [1 2 3 5 7]
Array2:  [2 3 4 5 6]

Array1 >  Array2:  [False False False False  True]
Array1 >= Array2:  [False False False  True  True]
Array1 <  Array2:  [ True  True  True False False]
Array1 >= Array2:  [ True  True  True  True False]


### Q2

In [36]:
ar3 = np.arange(30,71,2)
print("Even integers from 30 to 70: ", ar3)

Even integers from 30 to 70:  [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### Q3

In [39]:
print("3x3 identity matrix: \n", np.identity(3))

3x3 identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Q4

In [45]:
ar4 = np.arange(21)
print("Array: \n", ar4)
ar4[(ar4>=9) & (ar4<=15)] *= -1
print("After changing sign from (9,15): \n", ar4)

Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing sign from (9,15): 
 [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


### Q5

In [56]:
ar5 = np.diag([1, 2, 3, 4, 5])
print("5x5 diagonal matrix: \n", ar5)
ar5[1:3]

5x5 diagonal matrix: 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


array([[0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0]])

### Q6

In [61]:
ar6 = np.identity(5)
print("Sum of all numpy array: ", ar6.sum())
print("Sum of all numpy array rows: ", ar6.sum(axis=1))
print("Sum of all numpy array columns: ", ar6.sum(axis=0))

Sum of all numpy array:  5.0
Sum of all numpy array rows:  [1. 1. 1. 1. 1.]
Sum of all numpy array columns:  [1. 1. 1. 1. 1.]


### Q7

In [120]:
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)

np.savetxt('array_file.txt', x, fmt="%d") 
print("\nAfter loading:")
result = np.loadtxt('array_file.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

After loading:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


### Q8

In [124]:
print("Original arrays:")
print(ar1)
print(ar2)
print("\nTwo arrays are equal (element wise) or not :", np.equal(ar1, ar2))

Original arrays:
[1 2 3 5 7]
[2 3 4 5 6]

Two arrays are equal (element wise) or not : [False False False  True False]


### Q9|

In [116]:
ar7 = (np.random.rand(12)*100).reshape(4,3).astype("int64")
print("Array: \n", ar7)
ar7[[0,3]] = ar7[[3,0]]
print("\nAfter swapping: \n", ar7)

Array: 
 [[73 28 51]
 [68 80 47]
 [79 67 95]
 [31 78 70]]

After swapping: 
 [[31 78 70]
 [68 80 47]
 [79 67 95]
 [73 28 51]]


### Q10

In [131]:
a1=np.random.randint(10,size=(4)).reshape(2,2)
a2=np.random.randint(10,size=(4)).reshape(2,2)
print("",a1,"\nx\n",a2,"\n = \n", np.multiply(a1,a2))

 [[9 8]
 [2 0]] 
x
 [[5 6]
 [9 3]] 
 = 
 [[45 48]
 [18  0]]
